services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge