FROM node:18-slim as build

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:latest

COPY --from=build /dist /usr/share/nginx/html
COPY --from=build nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173

# Запускаем Vite
CMD ["nginx", "-g", "daemon off;"]